CREATE DATABASE wordpress;
CREATE USER wordpress@localhost IDENTIFIED BY 'admin123';
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
    ON wordpress.*
    TO wordpress@localhost;

FLUSH PRIVILEGES;